# Generated by Django 4.1 on 2022-08-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='origin',
            field=models.CharField(default='anterior', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='operation',
            field=models.CharField(max_length=40),
        ),
    ]
