# Generated by Django 4.1 on 2022-08-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0003_alter_logmodel_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='typewh',
            field=models.CharField(default='rdstation', max_length=20),
            preserve_default=False,
        ),
    ]
